backend/uclapi/roombookings/views.py

ignores negative inputs in case phil tries the api

---

backend/uclapi/roombookings/tests.py

We updated the code, and didn't change the tests. With the CI, that should hopefully never happen again :D
@jermenkoo all tests pass for me locally

Fix tests to account for changed serialisation

---

backend/uclapi/roombookings/token_auth.py

`ok` field added to decorator response

add `ok` field to token-auth-fails

---

backend/uclapi/roombookings/decorators.py
backend/uclapi/roombookings/views.py

decorater order fixed

---

backend/uclapi/roombookings/views.py

increases page limit
- [ yes] Is this code complete?
- [no ] Are tests done/modified?
No

increase page lmit

---

backend/uclapi/gunicorn_config.py
backend/uclapi/requirements.txt

Fixes gunicorn by switching it from aiohttp to gevent
- [Y] Is this code complete?
- [N/A] Are tests done/modified?
No
Need to `pip install -r requirements.txt` due to gevent being needed now

Switch gunicorn over to gevent

---

backend/uclapi/requirements.txt
backend/uclapi/roombookings/helpers.py
backend/uclapi/roombookings/tests.py
backend/uclapi/roombookings/views.py
backend/uclapi/uclapi/settings.py

This PR adds rate limiting for the API - it limits on user's ID which is obtained through his token.
The set limit is 10k requests / day. The limit automatically resets on midnight next day.
https://github.com/uclapi/apiDocs/pull/17
No.
No.
No.

Fixing rate limiting

---

backend/uclapi/roombookings/helpers.py

Prettifying did not work for `bookings` endpoint previously.
No.
No.
No.

fixing prettyjson for bookings endpoint

---

.hound.yaml

Enables Hound CI for repository to find violations in GitHub's PRs.
No.
No.
No.
No.

Hound CI configuration

---

frontend/src/react/components/getStarted/Footer.jsx

Fixes a typo :octocat: 🐙 🐱 
cc @wilhelmklopp you should know better

PascalCase GitHub in Footer

---

README.md

Update the readme with new testing instructions
N/A
No

Update readme with new testing instructions

---

backend/uclapi/roombookings/management/commands/update_gencache.py
backend/uclapi/roombookings/tests.py
backend/uclapi/roombookings/views.py
backend/uclapi/uclapi/settings.py

Bumps `setid` to the new academic year 🎓 
not applicable
No
none

Update setid to LIVE-17-18

---

backend/uclapi/dashboard/templates/shibboleth_error.html

Removes dysfunctional button that may have been confusing for users
not applicable
No
Nothing special

Remove dysfunctional button from shibboleth_error

---

backend/uclapi/dashboard/views.py
backend/uclapi/oauth/views.py

For example: Removes temporary shib workaround from before
- [] Are tests done/modified?
No

Remove temporary shib workaround

---

frontend/src/react/components/appForm.jsx

i just swapped the buttons when creating a new app on the dashboard because it was really annoying

swapped cancel and create buttons on dashboard

---

backend/uclapi/timetable/views.py

The timetable app has some redundant code pertaining to getting the user's token. This PR fixes that by making use of the decorator.
No
Just pull :)

Removes Redundant Token Code in Timetable

---

backend/uclapi/timetable/app_helpers.py
backend/uclapi/timetable/timetable_helpers.py
backend/uclapi/timetable/urls.py
backend/uclapi/timetable/views.py

Avoids duplicate data for labs
No
Just pull and restart uclapi

Match modgrpcode to avoid duplicate timetable entries for labs

---

backend/uclapi/timetable/timetable_helpers.py
backend/uclapi/timetable/urls.py
backend/uclapi/timetable/views.py

- Adds course data endpoints
- Stops you retrieving a mixture of existent and non-existent modules
No

Course Data and More Precise Custom Timetables

---

backend/uclapi/roombookings/helpers.py

Fixes the inconsistency in the paginated results.
- [ x] Is this code complete?
No
Merge it asap

fixes the inconsistency in data retrieval

---

backend/uclapi/roombookings/management/commands/trigger_webhooks.py

Fixes bug that led to empty payload being sent
No
Nothing special

Fix bug that led to empty payload being sent

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/src/react/components/app/Webhook.jsx
frontend/src/sass/pages/dashboard.scss

Fixes a bug where we'd store "undefined" in the db after a user entered no value.
Also makes the input text a different color to the placeholder, which was causing problems previously.
Also adds the package-lock.json file so that we can make sure we all have the same dependency installed and enable dependabot ✅ 
No

Fix "undefined" in webhook settings

---

backend/uclapi/timetable/views.py

Resolves #194 
Ish...clients expecting a 400 will now get some data back :)
Just update
Thanks go to @keelanfh for picking up on my 3am derp!

Fixes the get departments endpoint

---

backend/uclapi/dashboard/templates/agreement.html
backend/uclapi/dashboard/templates/dashboard.html
backend/uclapi/dashboard/templates/getStarted.html
backend/uclapi/oauth/templates/permissions.html

This makes the majority of our templates friendly to mobile devices. I came across this while implementing the OAuth flow for Veruto (mobile app). Some before, after pics for comparison
**Before**
**After**
**Before**
**After**
No

Improve mobile rendering of html pages

---

backend/uclapi/dashboard/tasks.py

Fixes our mailchimp task to do what the API expects (send JSON) and removes some error swallowing
No
Nothing special

Fix Mailchimp user adding

---

backend/uclapi/timetable/app_helpers.py
backend/uclapi/timetable/tasks.py

Caches a personal timetable in Redis for twelve hours when the first request is made to optimise repeat requests (e.g. when requesting every day in a week).
No
Just a normal pull
The solution is just to shove JSON into Redis. Whilst this is an acceptable solution for now, something prettier in the future would be preferred!

Redis Caching for Personal Timetable Endpoint

---

backend/uclapi/roombookings/views.py

Re-adds endpoint protection to the free rooms endpoint.
No
Just pull and reload.

Re-protects the free rooms endpoint

---

backend/uclapi/workspaces/occupeye.py
backend/uclapi/workspaces/urls.py
backend/uclapi/workspaces/views.py
frontend/src/react/components/documentation/Documentation.jsx
frontend/src/react/components/documentation/Routes/Workspaces/GetSensorHistoricalTimeData.jsx
frontend/src/react/components/documentation/Routes/Workspaces/GetSensorSummary.jsx
frontend/src/react/components/documentation/Sidebar.jsx

Adds historical data output
No
Re-run `feed_occupeye_cache` and reload uclapi

Adds Historical Data Endpoint

---

backend/uclapi/gunicorn_start.sh
scripts/supervisor/celery-uclapi.conf

I care about InfoSec these days :P This should reduce our attack surface by running our Python processes without root.
No
Ensure the permissions are set on the log files to be owned by ubuntu. The whole repo folder can be chowned to ubuntu, too.

Reduces what is run as root

---

backend/uclapi/workspaces/day_cache.sh

Adds day cache script for new Cad-Cap work
Yes/No

Adds day cache script

---

backend/uclapi/workspaces/occupeye/cache.py
frontend/src/react/components/documentation/Routes/Workspaces/GetSensorHistoricalTimeData.jsx
frontend/src/react/components/documentation/Routes/Workspaces/GetSensorSummary.jsx

Resolves #369
Yes (except it returns the API back to what is described in the docs)
Re-run full cache

[Hotfix] Fixes Summary Endpoint Data Types

---

backend/uclapi/roombookings/management/commands/trigger_webhooks.py

Adds additional logging for webhooks so that we can better debug what's not working
~- [ ] Are tests done/modified?~
~- [ ] Are docs written for this PR? (if applicable)~
No

Add more logging for webhooks

---

backend/uclapi/roombookings/management/commands/update_gencache.py
backend/uclapi/roombookings/views.py

Enables ICH Data for the HVAC team
No
Update Gencache

Adds ICH Data

---

frontend/.babelrc
frontend/package-lock.json
frontend/package.json

Latest Node and npm required.
Fixes building with newer versions of React and Babel.
No

Fixes building and updates some dependencies.

---

backend/uclapi/workspaces/image_builder.py
backend/uclapi/workspaces/occupeye/cache.py
frontend/src/components/documentation/Routes/Workspaces/GetSensorHistoricalTimeData.jsx

Fixes live images and caching when historical data is unavailable.
Also better explains in documentation what happens if historical data for a survey is unavailable.
No
Redeploy docs and update endpoints and cron.

Fixes to Workspaces API

---

backend/uclapi/timetable/amp.py
frontend/src/components/documentation/Routes/Timetable/GetDataModules.jsx

Adds the `student_type` parameter to AMP responses (resolves #863).
No (more data is added, but nothing is changes or removed)
Redeploy

Adds Student Type parameter to AMP responses

---

backend/uclapi/common/helpers.py
backend/uclapi/manage.py

Should get rid of the annoying error when running the API
No
Make sure this doesn't break anything and merge away!

Removes seemingly unnecessary dotenv import in common.helpers

---

backend/uclapi/oauth/tests.py
backend/uclapi/oauth/views.py

Gives correct error message for no callback url specified.
No
none
closes #946

Return correct message for no callback url

---

.gitignore
backend/uclapi/common/decorators.py
backend/uclapi/common/helpers.py
backend/uclapi/common/tests.py
backend/uclapi/oauth/tests.py
backend/uclapi/oauth/views.py
backend/uclapi/resources/views.py
backend/uclapi/roombookings/helpers.py
backend/uclapi/roombookings/management/commands/update_gencache.py
backend/uclapi/roombookings/views.py
backend/uclapi/search/views.py
backend/uclapi/timetable/management/commands/update_timetable_gencache.py
backend/uclapi/timetable/views.py
backend/uclapi/workspaces/occupeye/cache.py
backend/uclapi/workspaces/views.py
frontend/src/components/documentation/Meta/Welcome.jsx
frontend/src/components/documentation/Sidebar.jsx

Adds Last-Modified Header
No
Just deploy!
closes #839

Redis-based Last-Modified Header

---

backend/uclapi/manage.py

Re-adds read_dotenv, but with super powers

---

backend/uclapi/uclapi/settings.py

Hotfix for `collectstatic`
No
collectstatic

Fixes collectstatic for WebPack bundles

---

backend/uclapi/uclapi/wsgi.py

Fixes a slew of bugs in `wsgi.py`
No
Reload

Fixes WebPack Stats Downloading

---

backend/uclapi/timetable/app_helpers.py
backend/uclapi/timetable/management/commands/test_personal_timetable.py
frontend/src/components/documentation/Routes/OAuth/OAuthIntro.jsx

Speeds up timetable speed.
Needs a custom script/app written to check we do just remove the duplicate entries. On average i've found a speed-up of 33-41% in testing so far. This is just the first pass though of reducing postgresql queries. No Redis or Prepared queries have been implemented yet.
No
closes #467 
closes #983

Timetable speed-up

---

backend/uclapi/oauth/views.py

Fixes #999
No, it adds another field
Just git update

Adds access_token in response

---

backend/uclapi/workspaces/occupeye/cache.py

Resolves #1013 
No
Re-run full OccupEye cache

Ensures that even bad trigger types are stringified to avoid Redis errors

---

backend/uclapi/dashboard/api_applications.py
backend/uclapi/dashboard/tests.py

Adds test for successful regen of an app token.
no

More tests! 70%?! (Also 1 bug fix)

---

backend/uclapi/timetable/app_helpers.py

Hotfix: Add check if module has attribute modgrpcode

---

README.md

as title says...
no
n/a
closes #1076

add info about workspace caching in readme.md

---

frontend/src/components/getStarted/StagingBanner.jsx
frontend/src/components/getStarted/getStarted.jsx
frontend/src/sass/getStarted.scss

Adds a banner at the top to warn you that you are on our staging unstable branch.
no
re-build front-end provided this isn't done automatically?
closes #1078

Adds warning if you're on staging.ninja

---

backend/uclapi/requirements.txt

For example: Changes the way we retrieve bookings.
Yes/No

Fixes dependabots fuck-up/mine?

---

backend/uclapi/timetable/app_helpers.py

For example: Changes the way we retrieve bookings.
Yes/No

Hotfix for bymodule

---

backend/uclapi/workspaces/occupeye/cache.py

Deletes stale cache data.
Fixed #1024.
No
Delete occupeye:*
then run feed_occupeye_cache management command

Deleting stale cache data

---

backend/uclapi/common/decorators.py

Fixes throttling bug that occurs at midnight as Redis keys can't have TTL of 0
No
None

Fixed throttling bug that occurs at midnight

---

frontend/src/components/documentation/Routes/Workspaces/GetLiveImage.jsx

The example parameters given in the booking give a 400 error.
This PR changes parameters such that they give a valid live map.
No
Need to rebuild frontend docs?

Changing example to give valid parameters

---

backend/uclapi/roombookings/tests.py
backend/uclapi/roombookings/views.py

Adds correct response code when results_per_page is of incorrect type.
No
None

Booking status code fix

---

backend/uclapi/timetable/app_helpers.py

Checks that variable is a string before calling the strip() method.
No

Fixing bug when event has null for lecturerid

---

backend/uclapi/dashboard/api_applications.py
backend/uclapi/roombookings/management/commands/trigger_webhooks.py

should fix #1214 so that when we delete an app we also delete its webhook.
Yes/No
We need to go through all apps which are deleted and dis-able their webhook.

Deletes webhooks

---

frontend/README.md
frontend/package-lock.json
frontend/package.json
frontend/src/sass/getStarted.scss

As the title says. Resolves #1343
Yes/No
Need to build & upload static assets.

Closed the gap on uclapi.com

---

backend/uclapi/oauth/views.py

Fixing 500 error when not receiving an expected header
No

Fixing 500 error when not receiving an expected header

---

backend/uclapi/common/decorators.py
backend/uclapi/dashboard/api_applications.py
backend/uclapi/dashboard/tasks.py
backend/uclapi/dashboard/tests.py
backend/uclapi/dashboard/views.py
backend/uclapi/dashboard/webhook_views.py
backend/uclapi/oauth/views.py

Removes Keen Completely
No
Disable celery task?

Removing keen

---

backend/uclapi/dashboard/views.py

Fixing crash in dashbaord when not receiving department from Shibboeth
No
None

Fixing crash in dashbaord when not receiving department from Shibboeth

---

backend/uclapi/dashboard/views.py

Fixes a regression which casued an infinite loop
Yes/No

Fixing infinite loop

---

backend/uclapi/oauth/views.py

Fixes another regression in the my apps shibboleth callback which casued an infinite loop
Yes/No

Fixing infinite loop in other shibboleth callback

---

frontend/src/components/layout/views/CodeView.jsx

Fixes an issue preventing staging from rendering currently
No

Fixederror causing homepage to not render

---

frontend/src/components/layout/data/app_pages.jsx
frontend/src/components/layout/data/team_members.jsx
frontend/src/pages/AboutPage.jsx

Fixes a lack of punctuation and a typo
No

rewrote the description of the app with punctuation and fixed a typo

---

frontend/src/components/layout/data/homepage_constants.jsx

Fixes whitespace before and after FAQ links
Yes/No

Update whitespace in FAQ link text

---

frontend/src/components/layout/data/homepage_constants.jsx

For example: Changes the way we retrieve bookings.
Yes/No

fix spaces correctly

---

backend/uclapi/workspaces/occupeye/constants.py

Updates locations for workspaces
Yes/No

Update locations of workspaces

---

backend/uclapi/roombookings/tests.py

Fixes a test that was making an unnecessary DB connection.
Yes/No

Remove oracle connection in test

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/layout/Items.jsx
frontend/src/components/layout/NavBar.jsx
frontend/src/components/layout/views/CardView.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/Marketplace.jsx
frontend/webpack.prod.js

This avoids using MiniCssExtract due this [issue](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/386) and uses StyleLoader instead for production builds.
No
Rebuild frontend

Fix webpack config

---

frontend/src/components/layout/containers/Row.jsx
frontend/src/pages/AppPage.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/Marketplace.jsx

Makes buttons on homepage horizontally aligned again
Yes/No

Fix buttons on homepage

---

backend/uclapi/workspaces/occupeye/constants.py

The classic delete the survey and reupload the same (maybe slightly modified) survey has occured. One waits for the time when they simply edit the image and cause us less problems, but meanwhile we'll update the staff survey list... 
Human (visual) based `make && make test`; the test being looks like valid Python.

Update staff surveys

---

backend/uclapi/oauth/tests.py
backend/uclapi/oauth/views.py

Oauth auto allow

---

.travis.yml

Fixes travis deployment (for real this time)
- increases nodejs memory limit because webpack takes that much memory and fails when it doesn't get it
- builds (but does not deploy) frontend assets on PR branches as well (previously, frontend assets were only built on the master branch)
No

Fix nodejs installation

---

frontend/src/pages/Authorise.jsx

* Fix a typo in `Authorise.jsx`
Yes/No

🐛 BUGFIX: Fix Authorise.jsx

---

backend/uclapi/timetable/app_helpers.py
backend/uclapi/timetable/personal_timetable.py
backend/uclapi/timetable/sql/generate_student_timetable_template.sql

This patch handles timetable events that have no corresponding bookings
attached to them. This can occur during a "normal" year, but this is
especially prevalent during COVID-19 with online lectures dominating
people's timetables. Interestingly, this was already handled in
_get_timetable_events(), which is still used in some of the Python
only endpoints. Hence, the logic to handle this is adapted into parts
of the SQL and in the serialisation that still happens on the Python
side, where appropriate.
For example: Changes the way we retrieve bookings.
Yes/No

Handle timetable events with no bookings

---

frontend/src/components/documentation/Routes/OAuth/Authorise.jsx

I missed a function definition when writing the OAuth python sample code (oops). This adds it in
No
Build & redeploy frontend pls, thanks

🐛 Add in missing function definition in docs

---

backend/uclapi/dashboard/views.py

Fix error_404 and error_500 to return correct error codes.
No

🐛 Status code from error_404 and error_500 views

---

backend/uclapi/roombookings/management/commands/insert_locations.py

Resolve CWE-20 in roombookings.insert_locations, this poses an almost non-existent security risk as the http://www.ucl.ac.uk/efd/roombooking site is non malicious.
No

🔒 Resolve CWE-20

---

.github/workflows/CD.yml
.github/workflows/CI.yml

🚀 Trigger CD by Pull Request

---

.github/workflows/CD.yml

CD build frontend and remove wait

🚀 CD build frontend and remove wait

---

.github/workflows/CD.yml

🚀 CD add frontend dependencies

🚀 CD add frontend dependencies

---

.github/workflows/CD.yml

🚀 CD add backend dependencies

---

backend/uclapi/uclapi/settings.py

Upload to AWS without Redis key

🐛 Upload to AWS without Redis key

---

.github/workflows/CD.yml

🐛 Add ssh config file

---

.github/workflows/CD.yml

Change AWS_S3_STATICS_CREDENTIALS_ENABLED to True to upload new statics in CD

make CD deploy statics to S3

---

backend/uclapi/uclapi/settings.py

🚀 AWS bucket is public do not need authentication

🚀 AWS bucket is public do not need auth

---

.github/workflows/CD.yml

🚀 Provide env to frontend build. This is also possibly the cause of the production using the staging bucket.

🚀 Provide env to frontend build

---

frontend/webpack.prod.js

🚀 Github Actions Truthy

---

.github/workflows/CD.yml
.github/workflows/CI.yml
README.md

Adds cache to Github Actions and splits collect statics and deployment. Closes #3164, closes #3168

👷 Add Cache to Github Actions

---

backend/uclapi/oauth/app_helpers.py

The previous change was supposed to print out the missing fields,
however the logic was inverted :/
This is to help with debugging #3072, which is hard to reproduce locally.
No
None

Correctly return fields for debugging

---

.github/PULL_REQUEST_TEMPLATE.md

Update pull request template.
No

📝 Update Pull Request Template

---

backend/uclapi/uclapi/settings.py

CI from dependabot will currently fail due to SECRET_KEY not existing, see https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
No

🐛 Allow CI to pass from fork

---

.github/workflows/CI.yml

Follow up from #3253 trying to fix the same bug, migrate originally was not loading settings from uclapi.settings.
No

🐛 CI Use Settings When Running Migrate

---

backend/uclapi/uclapi/settings.py

Check if SECRET_KEY is empty, follow up #3265
No

🐛 CI Check if SECRET_KEY is Empty

---

.github/workflows/CI.yml

Add FORBIDDEN_CALLBACK_URLS to CI, they are already exposed in tests, follow up from #3270.
No

🐛 CI add FORBIDDEN_CALLBACK_URLS

---

frontend/package-lock.json
frontend/package.json

Emergency Update Webpack Loader, broken by https://github.com/uclapi/django-webpack-loader/commit/78025557436b869d1d3c34b6f62355eb198febf5
Yes/No

Emergency Update Webpack Loader

---

backend/uclapi/workspaces/day_cache.sh
backend/uclapi/workspaces/night_cache.sh

Update day_cache for occupeye

---

.github/workflows/CI.yml

As the title says. This should resolve the codecov upload failure (https://github.com/codecov/codecov-action/issues/330)
No

📦 dep: update codecov-action

---

backend/uclapi/common/middleware/health_check_middleware.py
backend/uclapi/uclapi/settings.py

Fix disallowed_host issues when ELB health check pings server
No

backend security: fix ELB health checks

---

.github/workflows/CD.yml
backend/uclapi/uclapi/settings.py
frontend/src/lib/ErrorReporting.jsx
frontend/webpack.prod.js

Update sentry DSN to add react keys along with production/staging environment
No

Fix Sentry DSN Issues

---

.github/workflows/CD.yml

github actions: cleanup staging CD

---

.github/helpers/auto-merge-approved-dependabot.py
.github/workflows/auto-merge-approved-dependabot.yml

Greenfrogs Dependabot Patch

---

.github/workflows/auto-merge-approved-dependabot.yml

github: dependabot use personal

---

.github/workflows/auto-merge-approved-dependabot.yml

github: add echo to github

---

.github/workflows/auto-merge-approved-dependabot.yml

github: echo redirect

---

.github/helpers/CODEOWNERS
.github/workflows/CODEOWNERS
.github/workflows/auto-merge-approved-dependabot.yml

github: codeowners

---

frontend/webpack.dev.js
frontend/webpack.prod.js

frontend webpack: file-loader

---

frontend/webpack.dev.js
frontend/webpack.prod.js

frontend webpack: remove url-loader limit

---

.github/workflows/CD.yml

github actions: update CD to be case sensitive

---

.github/workflows/codeql-analysis.yml

github actions: codeql to weekly

---

backend/uclapi/dashboard/api_applications.py
backend/uclapi/dashboard/app_helpers.py
backend/uclapi/dashboard/webhook_views.py

backend dashboard: allow localhost

---

backend/uclapi/dashboard/app_helpers.py
backend/uclapi/dashboard/tests.py

backend dashboard: allow http on non public

---

frontend/src/pages/Dashboard/Dashboard.jsx

frontend dashboard: remove https check on callback

---

backend/uclapi/oauth/app_helpers.py

backend oauth: log failed login

---

docker/deployment/nginx/util.sh

Switch to production for let's encrypt ssl certificate. Need to wait until 7th September to merge.

SSL Certificate for staging.ninja

---

.github/workflows/deploy.yml

github actions: specify branch for deployment

---

.github/workflows/deploy.yml

github actions: use personal token

---

.github/workflows/deploy.yml

github actions: force push deployment

---

.github/workflows/create-version.yml
.github/workflows/deploy.yml

github actions: create version

---

.github/workflows/create-version.yml

github actions: specify input for version

---

backend/uclapi/timetable/tasks.py
docker/deployment/docker-compose-staging.yml
docker/deployment/docker-compose.yml

run gencache using new celery "cronbox"
No

docker cron: celery-based gencache

---

backend/uclapi/uclapi/ourcelery.py

Adds missing gencache celery beat schedule
No

docker cron: add gencache cron schedule

---

.github/workflows/workflow.yml
backend/uclapi/uclapi/ourcelery.py
docker/deployment/docker-compose-staging.yml

Limit amount of resources the celery worker container can use. Should mitigate resource exhaustion.
No

docker cron: add resource limits for cron container

---

.github/workflows/combine-pr.yml

github workflow: add combine pr yml

---

backend/uclapi/dashboard/tasks.py

backend dashboard: disable mailchimp in staging

---

backend/uclapi/uclapi/ourcelery.py

docker cron: fix gencache schedule creation

---

docker/deployment/nginx/nginx-conf/conf.d/nginx.conf

docker nginx: add default server

---

backend/uclapi/timetable/tasks.py
backend/uclapi/uclapi/celery.py
docker/deployment/nginx/nginx-conf/conf.d/nginx.conf

backend celery: update periodic task

---

docker/deployment/cron/supervisor-conf/celery-beat-uclapi.conf

docker cron: update celery scheduler

---

docker/deployment/nginx/nginx-conf/conf.d/nginx.conf

docker nginx: add ssl to default

---

backend/uclapi/timetable/tasks.py

backend celery: move gencache update completion request

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

github actions: auto prune on full disk

---

backend/uclapi/uclapi/celery.py

backend celery: setup tasks after finalize

---

backend/uclapi/common/views.py
backend/uclapi/uclapi/celery.py
backend/uclapi/uclapi/urls.py

Adds a ping endpoint for use by Freshping, ?checks=1 can be added to run database, cache, and sentry checks.
No

backend common: add ping endpoint

---

backend/uclapi/uclapi/celery.py
backend/uclapi/workspaces/tasks.py

This completes the migration away from cronjobs, in favor of celery scheduled tasks.
No

backend celery: add occupeye cache to celery

---

backend/uclapi/workspaces/tasks.py

Adds healthcheck to Occupeye Celery Tasks

Add healthcheck to occupeye tasks

---

.github/workflows/deploy.yml
docker/deployment/docker-compose-production.yml
docker/deployment/docker-compose-staging.yml
docker/deployment/docker-compose.yml

docker production: add cron image

---

backend/uclapi/workspaces/occupeye/archive.py
backend/uclapi/workspaces/occupeye/endpoint.py

backend workspaces: skip archive on 404

---

backend/uclapi/workspaces/tasks.py

backend workspaces: show logging when task requested

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml
backend/uclapi/requirements.txt

github: increase memory for cron

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

github actions: export cron

---

frontend/package-lock.json
frontend/package.json

frontend deps: resolve npm security 2022-06

---

backend/uclapi/requirements.txt

Required to allow proper installation of django-postgrespool2
Please see: https://github.com/lcd1232/django-postgrespool2/issues/30
Yes/No

Pin SQLAlchemy version

---

backend/uclapi/requirements.txt

Bump flake8 to 5.0.4 and pycodestyle to 2.9.0

---

backend/uclapi/requirements.txt

Bump greenlet and gevent together as they depend on each other

---

backend/uclapi/timetable/tasks.py

healthcheck start event only if gencache not already running

---

uclapi.openapi.json

Update uclapi.openapi.json authorisation urls

---

backend/uclapi/requirements.txt

HOTFIX: fix DNS timeout

---

.github/workflows/deploy.yml
.github/workflows/workflow.yml

Upgrade GitHub Actions runners to Ubuntu 24.04
