backend/uclapi/roombookings/helpers.py
At the moment you will get an error when supplying the `start_datetime` and `end_datetime` parameter for the bookings endpoint. This PR fixes that.
@abdulfaizp pls test locally and merge.
=> Fix replace function usage

backend/uclapi/roombookings/views.py
Right now supplying the `descrip` parameter leaves you with a `500` error. This PR fixes that.
=> Fix description field

.travis.yml, README.md
This PR changes 2 (+1) things:
* adds codecov.io support to measure coverage of the codebase
* adds build badges (TravisCI, codecov) into README.md
* installs cx-Oracle from requirements.txt (as previously the version was hard-coded to 5.2.1 - the version before upgrade of requirements.txt)
No.
No.
The badges (esp. Travis CI) should get updated once merged into `master` branch.
=> Adding codecov.io (coverage) support

backend/uclapi/roombookings/helpers.py, backend/uclapi/roombookings/tests.py, backend/uclapi/roombookings/views.py
This PR automatically indents the `JsonResponse` object for user-friendliness. `PrettyJsonResponse` inherits from `JsonResponse` so that it still works with Django but the response looks nice.
No.
No.
No.
No.
=> pretty formatting JsonResponse

backend/uclapi/uclapi/UCLAPIAcceptableUsePolicy.txt
Adds a clause to the AUP to tell people that we'll be emailing them. This is to keep in line with the Amazon SES AUP.
A typo was also fixed. Yay!
- [ ✅] Is this code complete?
- [ N/A ] Are tests done/modified?
No
Just a git pull and restart of the API via supervisor. Nice 'n' easy!
=> Update AUP text with email notifications

backend/uclapi/dashboard/middleware/fake_shibboleth_middleware.py, backend/uclapi/dashboard/tests.py
Allows Shibboleth parameters to be passed via `GET` from Fake Shibboleth. This allows the auto mode of the recent PR on [fakeshibboleth](https://github.com/uclapi/fakeshibboleth) to work.
No
Nothing special at all :)
Noop :)
=> Add get parameter parsing for fakeshibboleth auto mode

backend/uclapi/dashboard/views.py, backend/uclapi/oauth/views.py
This PR fixes errors like this one: https://opbeat.com/ucl-api-team/ucl-api-team-backend/errors/23/
by establishing consistency between the workaround in `oauth/views.py` and `dashboard/views.py`
This PR also makes sure the login reminder is stored in a way that people can see it on the dashboard and are thus prompted to log in again via shibboleth.
No
normal deploy
=> Improve temp shib workaround and fix dashboard login error

backend/uclapi/dashboard/migrations/0011_auto_20170930_1600.py
Fixes the data migration that was missing from the webhook PR that got lost in the rebase/re-adding of migrations on top of OAuth migrations
No
Need to delete the last migration applied on staging (in migrations table)
Should be clean on production
@ChristopherHammond13
=> [Webhook] Re-add lost data migration

backend/uclapi/search/views.py
Ensures a 400 status code is sent when no search query param is supplied to `/search/people`.
No
This fixes #119
=> Fixes error response code when no search query is supplied

backend/uclapi/roombookings/management/commands/update_gencache.py, backend/uclapi/timetable/management/commands/update_timetable_gencache.py
This executes a raw query everytime buckets are refilled to ensure that the auto increment starts from 0 for the primary key ids. This also replaces the `Model.objects.all().delete()` with truncate. Using raw query should give some millisecond advantage.
=> restart autoupdate counter on the database from django itself

frontend/src/react/components/documentation/Routes/Timetable/GetPersonalTimetable.jsx, frontend/src/react/components/documentation/Routes/Timetable/GetTimetableByModules.jsx
The current docs refer to this JSON structure:
`{"foo": "bar"}`
as variously an object, a dict, and even a map. 
This is confusing when reading the docs, so I propose changing it to make it consistent.
Per the [JSON spec](http://json.org/), this is called an object, so I've gone with that, although I think the most important thing is that the wording is consistent. 
Would be interesting to see what you think :)
Yes/No
=> Change docs references to objects, dicts and maps 

frontend/src/react/components/documentation/Routes/Search/VersionHeader.jsx
Fixes documentation for the Search Endpoint by using an appropriate version header instead of the `roombookings` version header.
No
Just the usual, I guess? 🤷‍♂️ 
Even though the source file had the correct documentation, the Search docs showed the info from the room booking docs due to using an incorrect tag, I changed that tag to a new, `uclapi-search-version` header that seems to be consistent with the naming scheme. Maintainers, please tell me if there are any other links I'd have to change to actually create a new version header for the search docs.
What it is showing right now:
=> Changed Search Version Header

backend/uclapi/oauth/views.py
Should resolve #225 and #224 by allowing the `/oauth/token` endpoint to be accessed via GET and POST, instead of just GET.
No
Just update
=> Allows the OAuth token to be obtained via POST

backend/uclapi/.env.example, backend/uclapi/requirements.txt, backend/uclapi/uclapi/wsgi.py, backend/uclapi/workspaces/image_builder.py, backend/uclapi/workspaces/occupeye.py, backend/uclapi/workspaces/urls.py, backend/uclapi/workspaces/views.py, frontend/src/react/components/documentation/Documentation.jsx, frontend/src/react/components/documentation/Routes/Workspaces/GetImage.jsx, frontend/src/react/components/documentation/Routes/Workspaces/GetLiveImage.jsx, frontend/src/react/components/documentation/Sidebar.jsx
- Django Update
- Fixes the `runserver` issue
- Most importantly, adds SVG image generation to show every seat, live, on its map!
Yes
I have changed the image endpoint (but this hasn't been used yet so I'm not concerned)
Re-run OccupEye cache
=> Cadcap live images

backend/uclapi/oauth/scoping.py, backend/uclapi/oauth/urls.py, backend/uclapi/oauth/views.py, backend/uclapi/timetable/app_helpers.py, frontend/src/react/components/documentation/Documentation.jsx, frontend/src/react/components/documentation/Routes/OAuth/StudentNumber.jsx, frontend/src/react/components/documentation/Routes/OAuth/UserData.jsx, frontend/src/react/components/documentation/Sidebar.jsx
There has been a request from a student to be able to get a student's ID via OAuth. I've added this as a separate scope. The `oauth/user/data` endpoint will also tell the caller whether the user is a student or not.
Also done some fixes here and there to the OAuth code.
No
Just pull and restart uclapi
=> Adds student number scope to OAuth

backend/uclapi/requirements.txt
Adds Hi-redis as a requirment, thus allowing redis-py to use it by default.
- [Yes] Is this code complete?
- [Yes] Are tests done/modified?
- [N/A] Are docs written for this PR? (if applicable)
No
N/a
Closes #884
=> Add hiredis as requirment

backend/uclapi/uclapi/settings.py
Ensures that our AWS statics are made publicly readable as per the change in `django-storages` [here](https://github.com/jschneier/django-storages/issues/381).
No
Ensure in line with master when deploying statics from dev.
=> Sets default AWS bucket access policy to public-read for statics

.travis.yml, backend/uclapi/uclapi/settings.py, backend/uclapi/uclapi/wsgi.py, frontend/webpack.dev.js, frontend/webpack.prod.js
* `webpack-stats.json` now generated in `dashboard/statics`
* `wsgi.py` now downloads `webpack-stats.json` from S3 upon run
No
* `collectstatic` should upload `webpack-stats.json` to S3 bucket
=> Fix for webpack-stats.json deployment

backend/uclapi/uclapi/settings.py, backend/uclapi/uclapi/wsgi.py
Fixes our integration with `django-webpack-loader`.
Turns out that whilst `/` is not a valid path, `./` is. You're welcome, internet!
Refactors `wsgi.py` and `settings.py` a bit too...
No - it's a FIXING change!
Reload
=> Fixes Production! (I hope)

backend/uclapi/.env.example, frontend/package-lock.json, frontend/webpack.prod.js
* Fixes dumb bug that involves node reading `True` in .env as a string instead of a boolean
* Removed webpack-serve related note in `.env.example` because we don't use that anymore
* Also, `package-lock.json` seemed to be out of sync so have updated that as well
No
NA
=> Fix building in dev mode

.travis.yml, backend/uclapi/requirements.txt, backend/uclapi/uclapi/settings.py, backend/uclapi/uclapi/wsgi.py, frontend/webpack.dev.js
Migrates to a custom build of `django-webpack-loader` that lets us provide a `STATIC_URL` which will play nicer with `gunicorn`.
No
Deploy and restart the API
=> [WIP] Migrates us to a custom build of django-webpack-loader

backend/uclapi/workspaces/image_builder.py, frontend/src/components/documentation/Routes/Workspaces/GetLiveImage.jsx
Implements #1037 
Each <g> element in the SVG had an 'id' attribute which corresponds to the sensors id. Additional data on sensors can be retried from our Get Sensors (/workspaces/sensors) endpoint.
No
Rebuild docs.
=> Adding sensor ID to live map

backend/uclapi/workspaces/occupeye/cache.py, backend/uclapi/workspaces/occupeye/constants.py, frontend/src/components/documentation/Routes/Workspaces/GetLiveImage.jsx
Handles case when occupeye sends us a string instead of JSON.
Now correctly deletes surveys/maps/sensors/images that no longer exist.
Also deletes surveys that have gone paste their "EndDate"
Yes/No
=> Workspaces cache hot fix

backend/uclapi/roombookings/helpers.py, backend/uclapi/roombookings/management/commands/trigger_webhooks.py, backend/uclapi/roombookings/views.py
previously it appears lock.a meant use bucket a for timetable but lock.a mean do not use a for bookings. We did not notice this when unfying locks.
Yes/No
Run two caches to fix buckets as a safe measure
=> Unifies the way locking works

backend/uclapi/dashboard/views.py, backend/uclapi/oauth/tests.py, backend/uclapi/oauth/views.py, frontend/src/components/documentation/Routes/OAuth/Authorise.jsx, frontend/src/components/documentation/Routes/OAuth/UserData.jsx
This patch provides a complete fix to issues that occur when UCL's shibboleth
instance does not return certain headers.
The following fields are considered critical and cannot be empty. Absence of
these parameters will result in a 400 error code being returned:
1. eppn - used for finding user in DB. (We need to reconsider this...)
2. cn - unique in DB
3. employee_id - unique in DB, and used for determining is_student
The following fields are considered non-compulsory and instead replaced with an
empty string:
1. department
2. given_name
3. display_name
4. groups
This patch updates the documentation accordingly, and includes tests for certain
scenarios.
No - kind of. Those who rely on the department, given name, and display name being complete will now have this assumption broken.
Resolves …
=> Correctly deal with missing HTTP Headers

backend/uclapi/oauth/tests.py, backend/uclapi/oauth/views.py
In commit a81d6f580f3a3df04cb6839a60e326a63dd14359 an assumption was made that
a lack of the groups header meant that the user was an alumnus. This is not
strictly true: new students can also have a missing group header.
This patch partially reverts the above commit - we still deny access to the
dashboard for alumni (and consequently new students). However, this patch now
allows alumni (and consequenty new students) to successfully log into apps that
user our OAuth system.
- [x ] Is this code complete?
- [ x] Are tests done/modified?
- [ x] Are docs written for this PR? (if applicable)
No - but alumni are now allows to use OAuth apps.
=> Allow alumni to use UCL API OAuth

frontend/src/components/documentation/Routes/OAuth/UserData.jsx
The documentation for the oauth/user/data endpoint was incorrect. The following
corrections were made:
1. duplication of department field was removed.
2. The meaning of the cn field was explained.
3. The ok field was moved to the top for readability
=> Correcting OAuth User Data docs

.hound.yml, frontend/.eslintrc.hound.json, frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/test-hound.js
Add special eslint config for Hound, because Hound cannot resolve webpack alias paths.
See:
* https://github.com/uclapi/uclapi/pull/2524#issuecomment-657206118
* https://github.com/uclapi/uclapi/pull/2570#issuecomment-657206130
Yes/No
=> 🐶 hound-specific eslint config

backend/uclapi/dashboard/templates/404.html, backend/uclapi/dashboard/templates/500.html, backend/uclapi/dashboard/templates/about.html, backend/uclapi/dashboard/views.py, frontend/src/components/layout/Warning.jsx, frontend/src/pages/404.jsx, frontend/src/pages/500.jsx, frontend/src/pages/Warning.jsx, frontend/webpack.dev.js, frontend/webpack.prod.js
The following 3 pages no longer require any `initial_data` supplied by Django. They're now static, as they should be.
* Warning - warns the user they are not completely logged out on all UCL services
* Error 404
* Error 500
No
Redeploy frontend
I'm not sure why codecov is failing even though the change in coverage is 0.00%.
=> ✂  Decouple warning & error pages from django

.gitignore, backend/uclapi/.flake8.ini, backend/uclapi/dashboard/api_applications.py, backend/uclapi/dashboard/templates/dashboard.html, backend/uclapi/dashboard/tests.py, backend/uclapi/dashboard/urls.py, backend/uclapi/dashboard/views.py, frontend/package-lock.json, frontend/package.json, frontend/src/components/dashboard/App.jsx, frontend/src/lib/Api.js, frontend/src/pages/Dashboard.jsx
This allows the dashboard to exist as a static site on its own. Login and shibboleth is not yet done, but assuming a user is already logged in, a static version of the dashboard would 100% work.
Hound got upset whether I put the line break before or after the `+`, so I've ignored `W503` altogether.
I wrote a test for the new API I put in (`get_apps`), but test coverage for this part of the code is just low, hence the codecov fail.
No
=> ✂ Decouple dashboard from Django

backend/uclapi/oauth/views.py
Reverts uclapi/uclapi#2885
This code will raise `AtrributeError` as `get_students_by_upi()` returns a
`Students(A|B)` model, which contains none of `given_name`, `department` and
`display_name`.
=> Revert "Missing headers PR"

frontend/webpack.prod.js
Resolve CWE-312, only add the environmental variables required in a production build to webpack.
No
=> 🔒 Resolve CWE-312

backend/uclapi/uclapi/settings.py
Fixes a very very long running bug where we never actually set any AWS secrets.
=> 🚀 Use AWS_S3_STATICS_CREDENTIALS_ENABLED

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/codeql-analysis.yml
Limit the scope of dependabot and require us to review each pull request (and decide to skip, merge, ignore). The aim is to make us review these every single week by reducing the work load.
No
=> ⬆️ Limit the Scope of Dependabot

backend/uclapi/oauth/tests.py, backend/uclapi/oauth/views.py, frontend/src/components/documentation/Routes/OAuth/UserData.jsx
- Closes #3230 
- Removes unnecessary print statement in `/oauth/user/data` view.
No
None
=> Add sn and mail to OAuth user data

.github/.gitmessage, README.md
Add a git commit message template and include guidance in the readme. This is an attempt to try and make all commit messages consistent across contributors.
No
=> Add git commit message template

frontend/src/sass/common/uclapi.scss, frontend/webpack.dev.js, frontend/webpack.prod.js
Patches the controversial decision by webpack file loader to switch to using unflattened objects.
https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module
=> Migrate To url-loader

frontend/webpack.dev.js, frontend/webpack.prod.js
Turns out there is yet another way of inlining assets for deployment. This method was added in webpack v5, I really hope this method works with django statics.
You can read more about it here: https://webpack.js.org/guides/asset-modules/
=> frontend webpack: migrate to asset modules

frontend/src/lib/Api/DashboardApi.js
This PR attempts to resolve #3209 by catching errors thrown by the post request and returning the nice error message found in Django, rather than the generic "400 returned".
- [] Are tests done/modified?
- [] Are docs written for this PR? (if applicable)
No
=> Update Webhook Callback URL Error Message

backend/uclapi/uclapi/settings.py
Disable django.security.DisallowedHost from being reported to sentry.
=> backend settings: disable disallow host in sentry

CONTRIBUTING.md, README.md, README_SETUP.md
Currently new developers find it quite hard to make quick development changes to UCLAPI. This change to the README simplifies the process and ensures it takes less than 10 minutes to be fully setup.
Simplifies the readme to only contain docker setup instructions with old setup instructions moved to README_SETUP.md. Also moves git commit recommendations to the CONTRIBUTING.md file.
=> Simplify Readme and Setup

frontend/src/components/layout/Link.jsx, frontend/src/components/layout/NavBar.jsx, frontend/src/pages/Home/HomePage.jsx, frontend/src/sass/navbar.scss
Fixes the animation bug on mobile preventing the navbar from closing and updates the style. Also fixes the bouncing animation and replaces it with a spring animation. Also fixes the order on mobile so that the most important item is first.
Before, desktop:
After, desktop:
Mobile:
=> Update Navbar for Desktop and Mobile

backend/uclapi/libcal/tasks.py, backend/uclapi/libcal/tests.py, backend/uclapi/libcal/utils.py, backend/uclapi/libcal/views.py, frontend/src/components/layout/data/homepage_constants.jsx, frontend/src/pages/Home/HomePage.jsx, uclapi.openapi.json
This PR will add the new LibCal endpoints (#3004) to our OpenAPI config.
Added a new apiToken security scheme because an OAuth token is not actually needed to read non-personal LibCal data - a regular API token is suffifcient.
Non-personal read-only requests can be executed on the auto-generated OpenAPI docs, but not other requests because the OAuth security flow does not appear to be working.
No
Rebuild frontend.
@shu8 we might want to split this 6k+ line JSON file into separate files in the future, perhaps make an openapi folder and separate JSON files for workspaces, timetable, LibCal, etc.
Not sure why codecov seems to think coverage in `uclapi/settings.py` has gone down.
=> Add LibCal endpoints to OpenAPI

backend/uclapi/libcal/tests.py, backend/uclapi/libcal/tests_utils.py, backend/uclapi/libcal/utils.py, backend/uclapi/libcal/views.py, uclapi.openapi.json
Change GET bookings for libcal to only allow specific fields, rather than removing certain fields.
This means if the actual libcal endpoint adds any more sensitive fields in future, we won't return them to the user unwittingly.
No
=> libcal: use whitelist for sensitive endpoints instead of blacklist

backend/uclapi/common/decorators.py, backend/uclapi/common/tests.py
Rejects OAuth tokens if the corresponding app has been deleted.
Yes/No
=> Don't accept OAuth tokens belonging to deleted apps

backend/uclapi/workspaces/occupeye/archive.py
Hopefully prevents returning multiple sensors with the same ID
Gets sensor by full composite key instead of just sensor ID should fix: https://sentry.io/organizations/isd-api-team/issues/3305040895/events/eb104c788b3e4d99b214967ec91aa921/?project=5616849
Yes/No
=> Get sensor by full composite key

frontend/src/sass/common/uclapi.scss
Removes an unnecessary trailing comma after button definition in uclapi.scss
No
N/A
Closes #3453
=> remove unnecessary comma after button style definition

backend/uclapi/oauth/app_helpers.py, backend/uclapi/oauth/tests.py
We can concatenate the given name (forename) and surname instead.
Yes/No
=> Don't use Azure's "Surname, Forename" format for full name

backend/uclapi/oauth/app_helpers.py
Groups of type #microsoft.graph.directoryRole and maybe more don't have `onPremisesSamAccountName` nor `mailNickname` properties. We can ignore these because they aren't the type of groups we want.
No
=> Account for some AD groups not having the mailNickname

backend/uclapi/oauth/app_helpers.py
=> Add sentry exception catching to AD integrity errors
